### PR TITLE
Configure less driving for P&R results

### PR DESCRIPTION
**Pull request by leonardehrenfried**
As requested by @whitneys-pm this reduces the driving for the P&R results for Community Transit.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
cc @daniel-heppner-ibigroup @miles-grant-ibigroup 

@whitneys-pm: I've only applied it to test. Do they want to test first or should I apply it to prod as well?

**Comment by whitney-shavers-arcadis** [comment]
@leonardehrenfried This looks great. Please apply this change to PROD as well.

**Comment by miles-grant-ibigroup** [comment]
Feel free to merge once you've done that. We aren't doing reviews in here

**Comment by leonardehrenfried** [comment]
I don't have the permissions to do so.

**Comment by miles-grant-ibigroup** [comment]
Ah I'll get that fixed for next time

**Pull request merged**
